### ISSUE TITLE
Autoryzacja API

### ISSUE THREAD

**Issue by dwdzdc** [akai-org/lekarz#13]
Jeżeli chcemy robić API aplikacji potrzebujemy dać użytkownikom i aplikacjom możliwość autoryzacji przez API. Autoryzacja może się odbywać za pośrednictwem protokołu oauth2. Do naszej aplikacji django potrzebujemy przekazać przez API poświadczenia użytkownika, a potem zwrócić mu token, który będzie przesyłał w nagłówku każdego zapytania. Więcej na ten temat w poniższych linkach:

### Narzędzia do setupu w Django:
* https://django-oauth-toolkit.readthedocs.io/en/latest/

### Ogólny opis działania oAuth2
* https://sekurak.pl/oauth-2-0-jak-dziala-jak-testowac-problemy-bezpieczenstwa/
* https://medium.com/google-cloud/understanding-oauth2-and-building-a-basic-authorization-server-of-your-own-a-beginners-guide-cf7451a16f66

To duży task. W razie pytań piszcie, odpowiem.

**Comment by Szczepaniak-M** [comment]
Jestem na drugiej części Tutoriala i mam pytanie. Gdyż mam stworzyć nowe view i plik urls.py. One mają być stworzone w aplikacji interventions czy w jakiejś osobnej, np. tej API co jest do niej Issue?

**Comment by dwdzdc** [comment]
Mój błąd, nie przewidziałem tego. Przepraszam. Będzie lepiej jeżeli stworzysz do tego nową aplikację. Zrób to proszę i zamknij issue #18, zmergujemy obydwa issue w jednym PR.
