### ISSUE TITLE
Nowy moduł - API

### ISSUE THREAD

**Issue by dwdzdc** [akai-org/lekarz#18]
Jest pomysł, aby API było całkowicie osobnym modułem w aplikacji. Dlatego chciałbym utworzyć nową aplikację w projekcie, nazwać ją 'api' i umieszczać w niej tylko i wyłącznie widoki wyświetlające zażądane dane na podstawie mechanizmów z już istniejących aplikacji. API będzie oczywiście RESTowe. 

A więc po kolei:
* utworzyć nową aplikację, 
* utworzyć w niej plik urls.py, 
* w urls.py głównego folderu aplikacji lekarz utworzyć route /api/, które będzie odnosić się do urls.py w naszej nowej aplikacji. Więcej na ten temat tutaj: https://docs.djangoproject.com/en/2.2/topics/http/urls/#including-other-urlconfs

### Więcej na temat REST Api:
https://devszczepaniak.pl/wstep-do-rest-api/

**Comment by Szczepaniak-M** [comment]
Zrobiłem w branchu dev-13. Zamykam więc to Issue
