### ISSUE TITLE
Model doktora w aplikacji interventions

### ISSUE THREAD

**Issue by dwdzdc** [akai-org/lekarz#21]
Model doktora będzie działał na podobnej zasadzie do modelu pacjenta z #19. Będzie pod niego podłączony użytkownik relacją 1:1 i będzie zawierał dane typowo lekarskie. Szczerze nie wiem jakie to mogą być, więc na razie dajmy tak:

- specjalizacja, 
- oddział,
- numer legitymacji

**Comment by PatrykGrzegorek** [comment]
Ogólnie jak nikt nie weźmie tego do jt to mogę ja to wstawić bo juz to zrobiłem wraz z #22, ale nie chcę być samolubny to poczekam. Jesteśmy tu żeby sie uczyc i moze ktos by chciał akurat to zrobic. Ja juz zrobiłem inny i oznaczyłem sie jeszcze przy innym. Ten był krótszy i miałem 2min, wiec pomyslalem ze szybko klepne.

**Comment by dwdzdc** [comment]
@trebacz626, @KapelanJR, @AleksandraSwierkowska, @kolor200? Śmiało, issue nie gryzie, proste klepnięcie na parę minut roboty a ile zabawy przy tym!

**Comment by KacperSzmitko** [comment]
Dobra ja spróbuje to trzasnąć jak wrócę z uczelni.

**Comment by dwdzdc** [comment]
To przypisz się do taska proszę
