### ISSUE TITLE
Utworzenie modelu pacjent

### ISSUE THREAD

**Issue by dwdzdc** [akai-org/lekarz#4]
Model pacjent będzie "nakładką" na model użytkownika*. Będzie odpowiedzialny za przechowywanie wszelkich danych medycznych dotyczących użytkownika. W tym modelu lekarz będzie mógł na przykład notować różne uwagi odnośnie pacjenta, pacjent będzie miał przypisane indywidualne uwagi i przypomnienia lekarza, dane o chorobie. Pola:

- powiązany użytkownik,
- przyczyna hospitalizacji, 
- data hospitalizacji, 
- notatki lekarza odnośnie pacjenta (długie pole, TextField)

\* **Różnica pomiędzy użytkownikiem a pacjentem** - użytkownik czyli user w Django jest modelem odpowiedzialnym za podstawowe dane w aplikacji. Zawiera informacje takie jak email, imie, nazwisko, login, haslo. Może być powiązany z jakąś grupą użytkowników. Pacjent natomiast jest modelem reprezentującym dane medyczne na temat jakiegoś pacjenta, którego konto użytkownika jest z tym modelem powiązane. Ten model zawiera w sobie informacje stritce medyczne w powiązaniu do danego użytkownika. Czyli:

Użytkownik: 
 - imie, 
 - nazwisko, 
 - email
 - ...

Pacjent:
 - id uzytkownika, 
 - choroba, 
 - data przyjecia
 - ...

W przyszłości przewidujemy że użytkownikiem może być także lekarz, który po prostu nie będzie miał do siebie przypisanego modelu pacjenta ale jakiś inny, nowy, nazwany na przykład Doctor.

**Comment by PatrykGrzegorek** [comment]
Id_użytkownika to wybrać ten numerek? Czy stworzyć jakieś specjalne pole do ''stokenowania' użytkownika bo np id uzytkownika 1227 nic nie powie lekarzowi jak go bedzie miał poszukać czy przypisać? Może lepiej po imieniu i nazwisku? Może pesel?

**Comment by dwdzdc** [comment]
Otóż powiązanie w Django jest zrobione bardzo prosto. Nie potrzebujesz bawić się w niskopoziomowe IDkowanie. Django automatycznie nadaje klucz główny i na jego podstawie automatycznie pobiera klucz obcy z modelu powiązanego. Tutaj z pomocą może przyjść dokumentacja: https://docs.djangoproject.com/en/2.2/ref/models/fields/.

Interesuje Cię relacja jeden do jednego.
