### ISSUE TITLE
Nowy model - notification

### ISSUE THREAD

**Issue by dwdzdc** [akai-org/lekarz#42]
W module messages należy zrobić nowy model - Notification. Powiadomienia mogą przychodzić od pacjenta do doktora (np. pacjent pilnie potrzebuje pomocy lekarza), od automatu do pacjenta (np. zabieg rozpoczyna się za dwie godziny, prosimy rozpocząć przygotowania) albo od lekarza do pacjenta(ów) (np. informujemy o możliwości kupienia przysmaków na szpitalny korytarzu). Technicznie rzecz biorąc ma to być wiadomość, na którą odbiorca nie może odpowiedzieć i na której treść nie zawsze nadawca będzie miał wpływ (np. wezwanie doktora przez pacjenta będzie następowało przez naciśnięcie przycisku).

**Comment by trebacz626** [comment]
A on nie będzie w sumie taki sam jak messages tylko bedziemy go handlować inaczej?

**Comment by dwdzdc** [comment]
Właśnie zastanawiałem się nad tym. Myślę że na pewno dobrze będzie to rozdzielić, żeby powiadomienia klasyfikować osobno i wiadomości osobno, choćby dla oszczędności miejsca w przypadku powiadomień stałych bez możliwości wprowadzenia treści. Działać to będzie na podobnej zasadzie ale na razie idźmy w to, potem najwyżej usuniemy.
