### ISSUE TITLE
Dodawanie pacjenta - możliwość dodania pacjenta bez operacji

### ISSUE THREAD

**Issue by dwdzdc** [akai-org/lekarz#48]
Zakładamy że istnieje możliwość przyjęcia pacjenta bez potrzeby wprowadzania żadnych czekających go zabiegów bo np. czekamy na decyzję. W takim wypadku musi istnieć możliwość dodania pacjenta bez dodawania mu operacji z góry w panelu admina. W chwili obecnej tak sie nie da - dodawanie pacjenta jest równoważne z przypisaniem mu conajmniej jednej operacji.

**Comment by PatrykGrzegorek** [comment]
Nie mogę zapisać pacjenta, ponieważ w panelu administracyjnym nie ma pola na przypisanie 
usera do pacjenta. 

class PatientAdmin(admin.ModelAdmin):
    fieldsets = [('Informacje o pacjencie', **{'fields':['hospitalization_case', 'start_date', 'main_dr', 'dr_description']})]**
    inlines = [OperationInLine]

Jak dodałem to pole i przypisałem jakiegoś usera do pacjenta to mogłem go zapisać nie wypełniając żadnych pól w operacji(czyli wszystkie były puste)

class PatientAdmin(admin.ModelAdmin):
    fieldsets = [('Informacje o pacjencie', {'fields':[**'user',**'hospitalization_case', 'start_date', 'main_dr', 'dr_description']})]
    inlines = [OperationInLine]
