### ISSUE TITLE
Wystawienie aplikacji na serwer

### ISSUE THREAD

**Issue by dwdzdc** [akai-org/lekarz#52]
Aplikacja powoli nabiera kształtów toteż niedługo przyjdzie pora żeby wystawić ją na publiczny serwer. To jest ciężkie zadanie i wymaga dostępu do ssh, do zrobienia na którymś z listopadowych spotkań. Chętnych proszę o przypisywanie się do tego issue. Może być więcej niż jedna osoba.

**Comment by marcinlawnik** [comment]
Gdzie to wylądowało? Powstała jakaś instrukcja jak ogarniać pythonowe appki?
