### ISSUE TITLE
Aktualizacja README dla Windowsa

### ISSUE THREAD

**Issue by dwdzdc** [akai-org/lekarz#55]
Instrukcje setupu dla WIndwosa różnią się. Jeżeli znasz się na tym jak to setupować to zaktualizcuj proszę.

**Comment by simek456** [comment]
Jedyną różnicę jaką zauważyłem przy swojej instalacji to w kroku 3 piszesz:
 `env/Scripts/activate` zamiast
 `source env/bin/activate`
